#!/usr/bin/env python3
from __future__ import annotations

import os
import posixpath
import re
import shlex
import sys
import time
import traceback
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from typing import List, Optional, Set, Tuple

import paramiko

from PyQt6.QtCore import QThread, pyqtSignal
from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QLabel, QLineEdit, QPushButton,
    QTextEdit, QGridLayout, QProgressBar, QTableWidget, QTableWidgetItem,
    QHeaderView, QMessageBox, QCheckBox
)

# ---------------------------
# Discovery + generation logic
# ---------------------------

ASSET_EXTS = {
    ".html", ".htm", ".css", ".js", ".mjs",
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".ico",
    ".json", ".txt", ".map", ".woff", ".woff2", ".ttf", ".eot",
}
TEXT_EXTS = {".html", ".htm", ".css", ".js", ".mjs", ".json", ".txt", ".map"}

HREF_RE = re.compile(r"""(?is)\b(?:href|src)\s*=\s*["']([^"']+)["']""")
FORM_ACTION_RE = re.compile(r"""(?is)\baction\s*=\s*["']([^"']+)["']""")
FETCH_RE = re.compile(r"""(?is)\bfetch\s*\(\s*["']([^"']+)["']""")
XHR_RE = re.compile(r"""(?is)\bopen\s*\(\s*["'](?:GET|POST|PUT|DELETE|PATCH)["']\s*,\s*["']([^"']+)["']""")

PORT_RE = re.compile(r"(?i)\bport\b\s*[:=]\s*(\d{2,5})")
FLASK_RUN_RE = re.compile(r"(?i)\b--port\s+(\d{2,5})")
LISTEN_RE = re.compile(r":(\d{2,5})\b")

TEST_TEMPLATE = r'''# AUTO-GENERATED by Endpoint Test GUI
from __future__ import annotations

import os
import socket
import time
from urllib.parse import urljoin
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError

import pytest

BASE_URL = os.environ.get("CAPTIVE_BASE_URL", "{base_url_default}").rstrip("/") + "/"
MONITOR_HOST = os.environ.get("MONITOR_HOST", "{monitor_host_default}")
MONITOR_PORTS = {monitor_ports}

# Latency thresholds (milliseconds). Set to "0" to disable.
MAX_STATIC_MS = int(os.environ.get("MAX_STATIC_MS", "250"))
MAX_LINKED_MS = int(os.environ.get("MAX_LINKED_MS", "400"))
MAX_MONITOR_MS = int(os.environ.get("MAX_MONITOR_MS", "500"))

# Retries to smooth transient AP hiccups
HTTP_RETRIES = int(os.environ.get("HTTP_RETRIES", "2"))
HTTP_TIMEOUT_S = float(os.environ.get("HTTP_TIMEOUT_S", "3.5"))

def _http_get_timed(path: str):
    """
    Returns (status, headers, body, elapsed_ms)
    Retries on transient URLError.
    """
    url = urljoin(BASE_URL, path.lstrip("/"))
    last_exc = None

    for attempt in range(HTTP_RETRIES + 1):
        t0 = time.perf_counter()
        try:
            req = Request(url, headers={{{{"User-Agent": "pytest-endpoint-probe"}}}})
            with urlopen(req, timeout=HTTP_TIMEOUT_S) as resp:
                body = resp.read(4096)
                elapsed_ms = (time.perf_counter() - t0) * 1000.0
                return resp.status, dict(resp.headers), body, elapsed_ms
        except HTTPError as e:
            elapsed_ms = (time.perf_counter() - t0) * 1000.0
            return e.code, dict(getattr(e, "headers", {{{{}}}}) or {{{{}}}}), b"", elapsed_ms
        except URLError as e:
            last_exc = e
            if attempt >= HTTP_RETRIES:
                raise
            time.sleep(0.08 * (attempt + 1))

    raise last_exc  # pragma: no cover

def _assert_latency(name: str, ms: float, limit_ms: int):
    if limit_ms <= 0:
        return
    assert ms <= float(limit_ms), f"{{name}} too slow: {{ms:.1f}}ms > {{limit_ms}}ms"

@pytest.mark.parametrize("path", {static_endpoints})
def test_captive_portal_static_endpoints_return_200_and_fast(path: str):
    status, headers, body, ms = _http_get_timed(path)
    print(f"[LATENCY] static {{path}} -> {{status}} in {{ms:.1f}}ms")

    assert status == 200, f"Expected 200 for {{path}} but got {{status}}"
    assert body is not None
    _assert_latency(f"static {{path}}", ms, MAX_STATIC_MS)

@pytest.mark.parametrize("path", {linked_endpoints})
def test_captive_portal_linked_routes_reachable_and_fast(path: str):
    status, headers, body, ms = _http_get_timed(path)
    print(f"[LATENCY] linked {{path}} -> {{status}} in {{ms:.1f}}ms")

    assert status in (200, 301, 302, 401, 403), f"Unexpected status {{status}} for {{path}}"
    _assert_latency(f"linked {{path}}", ms, MAX_LINKED_MS)

def _tcp_connectable(host: str, port: int, timeout: float = 1.0) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False

@pytest.mark.parametrize("port", MONITOR_PORTS)
def test_monitor_responsive(port: int):
    if not _tcp_connectable(MONITOR_HOST, port, timeout=1.2):
        pytest.skip(f"Monitor not listening on {{MONITOR_HOST}}:{{port}}")

    url = f"http://{{MONITOR_HOST}}:{{port}}/"
    t0 = time.perf_counter()
    try:
        req = Request(url, headers={{{{"User-Agent": "pytest-monitor-probe"}}}})
        with urlopen(req, timeout=HTTP_TIMEOUT_S) as resp:
            _ = resp.read(2048)
            ms = (time.perf_counter() - t0) * 1000.0
            print(f"[LATENCY] monitor {{url}} -> {{resp.status}} in {{ms:.1f}}ms")
            assert resp.status in (200, 301, 302, 401, 403), f"Unexpected status {{resp.status}} for {{url}}"
            _assert_latency(f"monitor {{url}}", ms, MAX_MONITOR_MS)
    except HTTPError as e:
        ms = (time.perf_counter() - t0) * 1000.0
        print(f"[LATENCY] monitor {{url}} -> HTTPError {{e.code}} in {{ms:.1f}}ms")
        assert e.code in (301, 302, 401, 403), f"Unexpected HTTPError {{e.code}} for {{url}}"
        _assert_latency(f"monitor {{url}}", ms, MAX_MONITOR_MS)
    except URLError:
        ms = (time.perf_counter() - t0) * 1000.0
        print(f"[LATENCY] monitor {{url}} -> non-HTTP (TCP open) in {{ms:.1f}}ms")
        _assert_latency(f"monitor tcp {{url}}", ms, MAX_MONITOR_MS)
'''

def is_asset(path: str) -> bool:
    return os.path.splitext(path.lower())[1] in ASSET_EXTS

def is_text(path: str) -> bool:
    return os.path.splitext(path.lower())[1] in TEXT_EXTS

def norm_web_path(p: str) -> str:
    p = p.replace("\\", "/")
    if not p.startswith("/"):
        p = "/" + p
    p = re.sub(r"/{2,}", "/", p)
    p = p.replace("/./", "/")
    return p

def extract_candidate_paths(text: str) -> Set[str]:
    out: Set[str] = set()
    for rx in (HREF_RE, FORM_ACTION_RE, FETCH_RE, XHR_RE):
        for m in rx.finditer(text):
            out.add(m.group(1).strip())

    cleaned: Set[str] = set()
    for u in out:
        if not u or u.startswith("#"):
            continue
        if u.startswith(("http://", "https://", "//", "mailto:", "tel:", "data:")):
            continue
        u = u.split("#", 1)[0]
        cleaned.add(u)
    return cleaned

def urlify_static(rel_path: str) -> str:
    rp = rel_path.replace("\\", "/")
    if rp.lower() == "index.html":
        return "/"
    return norm_web_path(rp)

def guess_monitor_port_from_unit_text(unit_text: str) -> Optional[int]:
    m = FLASK_RUN_RE.search(unit_text)
    if m:
        return int(m.group(1))
    m = PORT_RE.search(unit_text)
    if m:
        return int(m.group(1))
    return None

def parse_junit(xml_text: str) -> List[dict]:
    root = ET.fromstring(xml_text)
    out: List[dict] = []
    suites = [root] if root.tag == "testsuite" else list(root.findall(".//testsuite"))

    for suite in suites:
        for tc in suite.findall(".//testcase"):
            name = tc.attrib.get("name", "")
            classname = tc.attrib.get("classname", "")
            t = tc.attrib.get("time", "0")
            status = "pass"
            msg = ""

            if tc.find("skipped") is not None:
                status = "skip"
                node = tc.find("skipped")
                msg = (node.attrib.get("message", "") if node is not None else "") or (node.text or "")
            elif tc.find("failure") is not None:
                status = "fail"
                node = tc.find("failure")
                msg = (node.attrib.get("message", "") if node is not None else "") or (node.text or "")
            elif tc.find("error") is not None:
                status = "error"
                node = tc.find("error")
                msg = (node.attrib.get("message", "") if node is not None else "") or (node.text or "")

            out.append(dict(
                name=name,
                classname=classname,
                time=t,
                status=status,
                message=(msg or "").strip(),
            ))
    return out

# ---------------------------
# SSH helpers
# ---------------------------

@dataclass
class SSHConfig:
    host: str
    user: str
    port: int
    key_path: str
    password: str

def ssh_connect(cfg: SSHConfig) -> paramiko.SSHClient:
    cli = paramiko.SSHClient()
    cli.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    kwargs = dict(hostname=cfg.host, username=cfg.user, port=cfg.port, timeout=12)
    if cfg.key_path.strip():
        kwargs["key_filename"] = cfg.key_path.strip()
    if cfg.password.strip():
        kwargs["password"] = cfg.password.strip()
    cli.connect(**kwargs)
    return cli

def ssh_run(ssh: paramiko.SSHClient, cmd: str) -> Tuple[int, str, str]:
    stdin, stdout, stderr = ssh.exec_command(cmd)
    out = stdout.read().decode("utf-8", errors="replace")
    err = stderr.read().decode("utf-8", errors="replace")
    code = stdout.channel.recv_exit_status()
    return code, out, err

def sftp_read_text(sftp: paramiko.SFTPClient, path: str, max_bytes: int = 512_000) -> str:
    with sftp.open(path, "rb") as f:
        data = f.read(max_bytes)
    return data.decode("utf-8", errors="replace")

def sftp_mkdir_p(sftp: paramiko.SFTPClient, remote_dir: str) -> None:
    remote_dir = remote_dir.replace("\\", "/").rstrip("/")
    if not remote_dir:
        return
    parts = remote_dir.split("/")
    path = ""
    for part in parts:
        if part == "":
            path = "/"
            continue
        path = ("/" + part) if path == "/" else (path + "/" + part)
        try:
            sftp.stat(path)
        except FileNotFoundError:
            sftp.mkdir(path)

def can_write_dir_sftp(sftp: paramiko.SFTPClient, remote_dir: str) -> bool:
    remote_dir = remote_dir.replace("\\", "/").rstrip("/") or "/"
    test_path = remote_dir.rstrip("/") + "/.write_test_tmp"
    try:
        with sftp.open(test_path, "w") as f:
            f.write("x")
        sftp.remove(test_path)
        return True
    except Exception:
        return False

def pick_writable_remote_path(
    ssh: paramiko.SSHClient,
    desired_path: str,
    *,
    fallback_dir: str = "/tmp",
    filename: str = "test_endpoints_generated.py",
) -> str:
    desired_path = desired_path.replace("\\", "/")
    desired_dir = posixpath.dirname(desired_path) or "/"

    sftp = ssh.open_sftp()
    try:
        try:
            sftp_mkdir_p(sftp, desired_dir)
            if can_write_dir_sftp(sftp, desired_dir):
                return desired_path
        except Exception:
            pass

        sftp_mkdir_p(sftp, fallback_dir)
        return posixpath.join(fallback_dir, f"{int(time.time())}_{filename}")
    finally:
        sftp.close()

def discover_files(ssh: paramiko.SSHClient, root_dir: str) -> List[str]:
    code, out, err = ssh_run(ssh, f"find {shlex.quote(root_dir)} -type f -print")
    if code != 0:
        raise RuntimeError(f"find failed: {err.strip()}")
    return [ln.strip() for ln in out.splitlines() if ln.strip()]

def build_endpoint_set(ssh: paramiko.SSHClient, root_dir: str) -> Tuple[List[str], List[str]]:
    files = discover_files(ssh, root_dir)
    assets = [f for f in files if is_asset(f)]

    def rel_from_root(abs_path: str) -> str:
        rd = root_dir.rstrip("/")
        if abs_path.startswith(rd + "/"):
            return abs_path[len(rd) + 1 :]
        return abs_path

    rels = [rel_from_root(f) for f in assets]
    static_eps = sorted({urlify_static(rp) for rp in rels})

    linked: Set[str] = set()
    sftp = ssh.open_sftp()
    try:
        for abs_path in assets:
            if not is_text(abs_path):
                continue
            try:
                txt = sftp_read_text(sftp, abs_path)
            except Exception:
                continue
            for u in extract_candidate_paths(txt):
                if u.startswith("/"):
                    linked.add(norm_web_path(u))
                else:
                    linked.add(norm_web_path(u.lstrip("./")))
    finally:
        sftp.close()

    linked_eps = sorted(linked - set(static_eps))
    return static_eps, linked_eps

def choose_monitor_ports(ssh: paramiko.SSHClient) -> List[int]:
    candidates: List[int] = []
    for svc in ("monitor.service", "lms-monitor.service", "lms_monitor.service", "lms.service"):
        _, txt, _ = ssh_run(ssh, f"systemctl cat {shlex.quote(svc)} 2>/dev/null || true")
        if txt.strip():
            p = guess_monitor_port_from_unit_text(txt)
            if p and p not in candidates:
                candidates.append(p)

    for p in (5000, 5050, 8000, 8080, 8888):
        if p not in candidates:
            candidates.append(p)

    _, out, _ = ssh_run(ssh, "ss -ltnp 2>/dev/null || netstat -ltnp 2>/dev/null || true")
    ports: Set[int] = set()
    for line in out.splitlines():
        for m in LISTEN_RE.finditer(line):
            try:
                ports.add(int(m.group(1)))
            except Exception:
                pass

    for p in sorted(ports):
        if p >= 1024 and p not in candidates:
            candidates.append(p)

    return candidates[:12]

from pathlib import Path
import json

def render_test_file_from_template(
    template_path: Path,
    *,
    static_eps: list[str],
    linked_eps: list[str],
    monitor_ports: list[int],
    base_url_default: str,
    monitor_host_default: str,
) -> str:
    tpl = template_path.read_text(encoding="utf-8")

    return (
        tpl
        .replace("__STATIC_ENDPOINTS__", repr(static_eps))
        .replace("__LINKED_ENDPOINTS__", repr(linked_eps))
        .replace("__MONITOR_PORTS__", repr(monitor_ports))
        .replace("__BASE_URL__", base_url_default)
        .replace("__MONITOR_HOST__", monitor_host_default)
    )

# ---------------------------
# Worker thread
# ---------------------------

class Worker(QThread):
    log = pyqtSignal(str)
    progress = pyqtSignal(int)
    step = pyqtSignal(str)
    tests_ready = pyqtSignal(list)
    finished_ok = pyqtSignal()
    finished_err = pyqtSignal(str)

    def __init__(
        self,
        cfg: SSHConfig,
        *,
        captive_root: str,
        repo_root: str,
        base_url_default: str,
        monitor_host_default: str,
        remote_test_path: str,
        run_pytest: bool,
    ) -> None:
        super().__init__()
        self.cfg = cfg
        self.captive_root = captive_root
        self.repo_root = repo_root
        self.base_url_default = base_url_default
        self.monitor_host_default = monitor_host_default
        self.remote_test_path = remote_test_path
        self.run_pytest = run_pytest

    def _emit(self, s: str) -> None:
        self.log.emit(s)

    def run(self) -> None:
        ssh = None
        try:
            self.progress.emit(0)
            self.step.emit("Connecting over SSH…")
            self._emit(f"[SSH] Connecting to {self.cfg.user}@{self.cfg.host}:{self.cfg.port}")
            ssh = ssh_connect(self.cfg)
            self._emit("[SSH] Connected.")
            self.progress.emit(10)

            self.step.emit("Checking captive portal directory…")
            _, out, _ = ssh_run(ssh, f"test -d {shlex.quote(self.captive_root)} && echo OK || echo MISSING")
            if "OK" not in out:
                raise RuntimeError(f"Remote captive portal dir missing: {self.captive_root}")
            self.progress.emit(18)

            self.step.emit("Checking repo root…")
            _, out, _ = ssh_run(ssh, f"test -d {shlex.quote(self.repo_root)} && echo OK || echo MISSING")
            if "OK" not in out:
                raise RuntimeError(f"Remote repo root missing: {self.repo_root}")
            self.progress.emit(22)

            self.step.emit("Discovering endpoints…")
            static_eps, linked_eps = build_endpoint_set(ssh, self.captive_root)
            self._emit(f"[DISCOVERY] Static endpoints: {len(static_eps)}")
            self._emit(f"[DISCOVERY] Linked routes: {len(linked_eps)}")
            self.progress.emit(35)

            self.step.emit("Discovering monitor ports…")
            monitor_ports = choose_monitor_ports(ssh)
            self._emit(f"[MONITOR] Candidate ports: {monitor_ports}")
            self.progress.emit(45)

            # --- NEW: generate tests from an on-disk template file (no .format brace issues) ---
            self.step.emit("Generating pytest file from template…")
            try:
                from pathlib import Path
                template_path = Path(__file__).resolve().parent / "templates" / "pytest_endpoints_template.py"
                if not template_path.exists():
                    raise RuntimeError(f"Missing template file: {template_path}")
                test_text = render_test_file_from_template(
                    template_path,
                    static_eps=static_eps,
                    linked_eps=linked_eps,
                    monitor_ports=monitor_ports,
                    base_url_default=self.base_url_default,
                    monitor_host_default=self.monitor_host_default,
                )
            except Exception as e:
                raise RuntimeError(f"Template-based generation failed: {e}")
            self.progress.emit(55)

            self.step.emit("Uploading tests to Pi…")
            desired_remote_test_path = self.remote_test_path.replace("\\", "/").strip() or "/tmp/test_endpoints_generated.py"

            remote_test_path = pick_writable_remote_path(
                ssh,
                desired_remote_test_path,
                fallback_dir="/tmp",
                filename="test_endpoints_generated.py",
            )
            remote_dir = posixpath.dirname(remote_test_path)

            self._emit(f"[DEBUG] desired_remote_test_path={desired_remote_test_path}")
            self._emit(f"[DEBUG] selected_remote_test_path={remote_test_path}")
            self._emit(f"[DEBUG] selected_remote_dir={remote_dir}")

            sftp = ssh.open_sftp()
            try:
                sftp_mkdir_p(sftp, remote_dir)
                with sftp.open(remote_test_path, "w") as f:
                    f.write(test_text)
            finally:
                sftp.close()

            self._emit(f"[UPLOAD] Wrote: {remote_test_path}")
            self.progress.emit(70)

            if not self.run_pytest:
                planned = [
                    dict(name="static_endpoints", classname="generated", time="0", status="pending",
                        message=f"{len(static_eps)} endpoints"),
                    dict(name="linked_routes", classname="generated", time="0", status="pending",
                        message=f"{len(linked_eps)} routes"),
                    dict(name="monitor_ports", classname="generated", time="0", status="pending",
                        message=f"{len(monitor_ports)} ports"),
                ]
                self.tests_ready.emit(planned)
                self.progress.emit(100)
                self.step.emit("Done (generated only).")
                self.finished_ok.emit()
                return

            self.step.emit("Running pytest remotely…")

            junit_remote = f"/tmp/endpoint_tests_{int(time.time())}.xml"
            log_remote = f"/tmp/endpoint_tests_{int(time.time())}.log"

            # Ensure pytest exists (auto-install if missing), run, capture rc, and log output deterministically.
            cmd = (
                f"cd {shlex.quote(self.repo_root)} && "
                f"python3 -m pip -q show pytest >/dev/null 2>&1 || python3 -m pip install --user -U pytest >/dev/null 2>&1; "
                f"python3 -m pytest -q --junitxml={shlex.quote(junit_remote)} "
                f"{shlex.quote(remote_test_path)} "
                f"> {shlex.quote(log_remote)} 2>&1; "
                f"echo __PYTEST_RC=$?"
            )
            self._emit(f"[RUN] {cmd}")

            _, out, err = ssh_run(ssh, cmd)
            if err.strip():
                self._emit("[stderr]\n" + err.rstrip())
            if out.strip():
                self._emit(out.rstrip())

            m = re.search(r"__PYTEST_RC=(\d+)", out)
            rc = int(m.group(1)) if m else 999
            self._emit(f"[RESULT] pytest exit code: {rc}")
            self.progress.emit(85)

            self.step.emit("Checking for JUnit XML…")
            _, ls_out, _ = ssh_run(ssh, f"ls -l {shlex.quote(junit_remote)} 2>/dev/null || echo MISSING")
            self._emit(f"[DEBUG] junit check: {ls_out.strip()}")

            if "MISSING" in ls_out:
                _, tail_out, _ = ssh_run(ssh, f"tail -n 120 {shlex.quote(log_remote)} 2>/dev/null || true")
                if tail_out.strip():
                    self._emit("[DEBUG] pytest log tail:\n" + tail_out.rstrip())
                raise RuntimeError(f"JUnit XML not found at {junit_remote}")

            self.step.emit("Fetching JUnit XML…")
            sftp = ssh.open_sftp()
            try:
                with sftp.open(junit_remote, "r") as f:
                    xml_text = f.read()
            finally:
                sftp.close()

            tests = parse_junit(xml_text)
            self.tests_ready.emit(tests)
            self.progress.emit(100)
            self.step.emit("Complete.")
            self.finished_ok.emit()

        except Exception:
            self.finished_err.emit(traceback.format_exc())
        finally:
            try:
                if ssh:
                    ssh.close()
            except Exception:
                pass

# ---------------------------
# GUI
# ---------------------------

class MainWindow(QMainWindow):
    def __init__(self) -> None:
        super().__init__()
        self.setWindowTitle("AP Mode Endpoint Test Generator + Runner")

        root = QWidget()
        self.setCentralWidget(root)

        grid = QGridLayout()
        root.setLayout(grid)

        self.host = QLineEdit("192.168.50.1")
        self.user = QLineEdit("pi")
        self.port = QLineEdit("22")
        self.key = QLineEdit("")
        self.password = QLineEdit("")
        self.password.setEchoMode(QLineEdit.EchoMode.Password)

        self.captive_root = QLineEdit("/AP_mode_wordpress_launcher/www/captive-portal")
        self.repo_root = QLineEdit("/AP_mode_wordpress_launcher")
        self.remote_test_path = QLineEdit("/AP_mode_wordpress_launcher/tests/generated/test_endpoints.py")

        self.base_url_default = QLineEdit("http://127.0.0.1")
        self.monitor_host_default = QLineEdit("127.0.0.1")

        self.run_pytest = QCheckBox("Run pytest after generating (recommended)")
        self.run_pytest.setChecked(True)

        row = 0
        grid.addWidget(QLabel("Host"), row, 0); grid.addWidget(self.host, row, 1)
        grid.addWidget(QLabel("User"), row, 2); grid.addWidget(self.user, row, 3)
        grid.addWidget(QLabel("Port"), row, 4); grid.addWidget(self.port, row, 5)
        row += 1
        grid.addWidget(QLabel("SSH key path"), row, 0); grid.addWidget(self.key, row, 1, 1, 3)
        grid.addWidget(QLabel("Password"), row, 4); grid.addWidget(self.password, row, 5)
        row += 1
        grid.addWidget(QLabel("Captive portal dir"), row, 0); grid.addWidget(self.captive_root, row, 1, 1, 5)
        row += 1
        grid.addWidget(QLabel("Repo root"), row, 0); grid.addWidget(self.repo_root, row, 1, 1, 5)
        row += 1
        grid.addWidget(QLabel("Remote test file path"), row, 0); grid.addWidget(self.remote_test_path, row, 1, 1, 5)
        row += 1
        grid.addWidget(QLabel("CAPTIVE_BASE_URL default"), row, 0); grid.addWidget(self.base_url_default, row, 1, 1, 2)
        grid.addWidget(QLabel("MONITOR_HOST default"), row, 3); grid.addWidget(self.monitor_host_default, row, 4, 1, 2)
        row += 1
        grid.addWidget(self.run_pytest, row, 0, 1, 3)

        self.btn = QPushButton("Generate + Run")
        self.btn.clicked.connect(self.on_run)
        grid.addWidget(self.btn, row, 3, 1, 3)

        row += 1
        self.step_label = QLabel("Idle.")
        self.progress = QProgressBar()
        self.progress.setRange(0, 100)
        grid.addWidget(self.step_label, row, 0, 1, 3)
        grid.addWidget(self.progress, row, 3, 1, 3)

        row += 1
        self.table = QTableWidget(0, 5)
        self.table.setHorizontalHeaderLabels(["Status", "Test", "Class", "Time", "Message"])
        self.table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
        self.table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
        self.table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
        self.table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.ResizeToContents)
        self.table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.Stretch)
        grid.addWidget(self.table, row, 0, 1, 6)

        row += 1
        self.log = QTextEdit()
        self.log.setReadOnly(True)
        grid.addWidget(self.log, row, 0, 1, 6)

        self.worker: Optional[Worker] = None

    def on_run(self) -> None:
        if self.worker and self.worker.isRunning():
            QMessageBox.information(self, "Busy", "A run is already in progress.")
            return

        try:
            port = int(self.port.text().strip() or "22")
        except ValueError:
            QMessageBox.critical(self, "Invalid port", "Port must be an integer.")
            return

        cfg = SSHConfig(
            host=self.host.text().strip(),
            user=self.user.text().strip(),
            port=port,
            key_path=self.key.text(),
            password=self.password.text(),
        )

        self.btn.setEnabled(False)
        self.table.setRowCount(0)
        self.log.clear()
        self.progress.setValue(0)
        self.step_label.setText("Starting…")

        self.worker = Worker(
            cfg,
            captive_root=self.captive_root.text().strip(),
            repo_root=self.repo_root.text().strip(),
            base_url_default=self.base_url_default.text().strip(),
            monitor_host_default=self.monitor_host_default.text().strip(),
            remote_test_path=self.remote_test_path.text().strip(),
            run_pytest=self.run_pytest.isChecked(),
        )
        self.worker.log.connect(self.append_log)
        self.worker.progress.connect(self.progress.setValue)
        self.worker.step.connect(self.step_label.setText)
        self.worker.tests_ready.connect(self.populate_table)
        self.worker.finished_ok.connect(self.on_ok)
        self.worker.finished_err.connect(self.on_err)
        self.worker.start()

    def append_log(self, s: str) -> None:
        self.log.append(s)

    def populate_table(self, tests: list) -> None:
        self.table.setRowCount(0)

        def add_row(status: str, name: str, classname: str, t: str, msg: str) -> None:
            r = self.table.rowCount()
            self.table.insertRow(r)
            self.table.setItem(r, 0, QTableWidgetItem(status))
            self.table.setItem(r, 1, QTableWidgetItem(name))
            self.table.setItem(r, 2, QTableWidgetItem(classname))
            self.table.setItem(r, 3, QTableWidgetItem(t))
            self.table.setItem(r, 4, QTableWidgetItem((msg or "")[:4000]))

        for tc in tests:
            add_row(
                tc.get("status", "unknown"),
                tc.get("name", ""),
                tc.get("classname", ""),
                str(tc.get("time", "0")),
                tc.get("message", ""),
            )

        counts = {}
        for tc in tests:
            counts[tc.get("status", "unknown")] = counts.get(tc.get("status", "unknown"), 0) + 1
        self.append_log(f"[SUMMARY] {counts}")

    def on_ok(self) -> None:
        self.btn.setEnabled(True)
        QMessageBox.information(self, "Done", "Generation (and run, if selected) completed.")

    def on_err(self, msg: str) -> None:
        self.btn.setEnabled(True)
        self.append_log(msg)
        QMessageBox.critical(self, "Error", "Run failed. See log for details.")

def main() -> int:
    app = QApplication(sys.argv)
    w = MainWindow()
    w.resize(1200, 800)
    w.show()
    return app.exec()

if __name__ == "__main__":
    raise SystemExit(main())
