interface=uap0
driver=nl80211
ssid=BetaBox
hw_mode=g
channel=7
wmm_enabled=1
auth_algs=1
wpa=2
wpa_passphrase=BetaBox
rsn_pairwise=CCMP

interface uap0
  static ip_address=192.168.50.1/24
  nohook wpa_supplicant

